# Console log
logging:
  level:
    org:
      springframework: off

# Spring
spring:
  main:
    banner-mode: "off"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: false
      simple:
        default-requeue-rejected: false